print("you will be asked to enter a shape.")
print("valid shapes are... circle, square, rectangle, triangle, parallelogram, and trapezium.")
print()
print()
print("you will then be asked for the needed values, such as the length, width, height etc.")